services:
  angular:
    image: angular:local
    container_name: angular
    restart: unless-stopped
    user: vscode
    volumes:
      - dotfiles:/home/vscode
      - ./web:/app
    # ports:
    #   - "4200:4200"
    working_dir: /app
    # command:  bash start.sh
    
  db:
    image: mariadb:local
    container_name: db
    restart: unless-stopped
    # ports:
    #   - "3306:3306"
    environment:
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      PRODUCTION: ${PRODUCTION}
    volumes:
      - dotfiles:/home/vscode
      - ./database/data:/var/lib/mysql
      - ./database/template:/docker-entrypoint-initdb.d

  php:
    image: php:local
    container_name: api
    restart: unless-stopped
    command: "bash start.sh"
    working_dir: /app
    user: vscode
    ports:
      - "80:80"
    volumes:
      - dotfiles:/home/vscode
      - ./api:/app
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}

volumes:
  dotfiles: